name: reproduction
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.9.4
  - bioconda::snakemake-minimal=6.2.1
  # Otherwise, snakemake throws an error (see https://git.io/JRckv)
  - conda-forge::smart_open=3
  - conda-forge::mne=0.23.0
  - conda-forge::autoreject=0.2.2
  # Only necessary because of a bug in autoreject 0.2.2 (see https://git.io/J46B9)
  - scikit-learn=0.23
  - conda-forge::r-base=4.1.1
  - conda-forge::r-rmarkdown=2.10
